// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhuwRG2eEIxC-U9blkXU8Nj83AThTmS2k',
    appId: '1:752026391108:web:f59b19d464bcaf662ba211',
    messagingSenderId: '752026391108',
    projectId: 'fir-project-8ac1d',
    authDomain: 'fir-project-8ac1d.firebaseapp.com',
    storageBucket: 'fir-project-8ac1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJG2gXWaOaIi1wweS47jX3EjrdrumiDkg',
    appId: '1:752026391108:android:938c6c500f9343d32ba211',
    messagingSenderId: '752026391108',
    projectId: 'fir-project-8ac1d',
    storageBucket: 'fir-project-8ac1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-EL7TkNSIaoJ96F01IvbAnDxmRy9w-E',
    appId: '1:752026391108:ios:b3e43d7987f760c62ba211',
    messagingSenderId: '752026391108',
    projectId: 'fir-project-8ac1d',
    storageBucket: 'fir-project-8ac1d.appspot.com',
    iosClientId: '752026391108-fa4bfut58c8mb0v77kbs8ekds6b3lti6.apps.googleusercontent.com',
    iosBundleId: 'com.example.introMobileProject',
  );
}
